---
- import_tasks: bootstrap.yml
  become: "yes"

- import_tasks: upgrade.yml
  become: "yes"

- import_tasks: hostname.yml
  become: "yes"
  when: hostvars[inventory_hostname].ansible_connection != "docker"

- import_tasks: ssh.yml
  become: "yes"
