---
- name: ensure openssh-server is installed
  apt:
    name: "{{item}}"
    state: present
    force_apt_get: "yes"
  with_items:
    - openssh-server

- name: Set authorized key took from file
  authorized_key:
    user: "{{ ansible_user | default('root') }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    line: "PasswordAuthentication no"
    state: present
  notify: reload ssh
